DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;

DROP TABLE MEMBER_T;
CREATE TABLE MEMBER_T (
    MEMBER_NO NUMBER NOT NULL,
    ID VARCHAR2(50 BYTE) NOT NULL UNIQUE,
    NAME VARCHAR2(50 BYTE),
    GENDER VARCHAR2(5 BYTE),
    ADDRESS VARCHAR2(50 BYTE),
    CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_NO)
);

SELECT MEMBER_NO, ID, NAME, GENDER, ADDRESS 
    FROM (SELECT ROW_NUMBER() OVER(ORDER BY MEMBER_NO DESC) AS RN, MEMBER_NO, ID, NAME, GENDER, ADDRESS
            FROM MEMBER_T)
  WHERE RN BETWEEN 1 AND 2;          
    